name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        node-version: [24.x]
        registry-url: ['https://registry.npmjs.org']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ matrix.registry-url }}
      - name: 'Installing build deps'
        run: npm i -g pnpm@10.25.0
      - name: 'Installing deps'
        run: pnpm i
      - name: 'Build'
        run: pnpm build
      - name: 'Publish'
        run: pnpm publish --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
